# Change these first
owner: yamisskey # Your GitHub organization or username, where this repository lives
repo: uptime.yami.ski # The name of this repository

sites:
  - name: Misskey
    url: https://yami.ski
  - name: CTF
    url: https://ctf.yami.ski
  - name: Element
    url: https://element.yami.ski
  - name: SearXNG
    url: https://search.yami.ski

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.yami.ski
  # baseUrl: /your-repo-name
  logoUrl: https://drive.yami.ski/files/ca1ff29d-dbaf-487a-925d-342ba1063116.webp
  name: Status
  introTitle: '**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub.'
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/yamisskey/uptime.yami.ski). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees: # Users to assign downtime issues (optional)
  - hitalin
